Feature/has specification
4Soft-de/vec-model pull request #39
Opened 2020-11-20 13:08 UTC by takebene

## Pull Request

- [ ] I have checked for similar PRs.
- [ ] I have read the [contributing guidelines](https://github.com/4Soft-de/vec-model/blob/develop/.github/CONTRIBUTING.md).

### Changes

- [ ] Code
- [ ] Documentation
- [ ] Other: 

### Description

Added two new interfaces:

- HasSpecification 
- HasRoles

2020-11-23 08:23 UTC, beckerjohannes requested changes

2020-11-23 08:23 UTC, beckerjohannes commented on README.md
> +</dependency>
Das sollte doch nicht notwendig sein, oder? Eigentlich muss das doch eine transitive Dep von 113 und 120 sein.

2020-11-23 09:06 UTC, takebene commented on README.md
> +</dependency>
Ich wollte es nur vollständig haben. Dann entferne ich das Modul aus der Readme.

2020-12-18 10:11 UTC, beckerjohannes approved these changes

2020-12-18 10:14 UTC, merged